version: "3"
services:
  web:
    build:
      context: .
      dockerfile: WebDockerfile
    volumes:
      - ./work:/opt/app
    ports:
      - 80
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: PHPDockerfile
    volumes:
      - ./work:/opt/app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
    depends_on:
      - database
  database:
    build:
      context: .
      dockerfile: DatabaseDockerfile
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      # - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
