version: "3"
services:
  web:
    build: ./nginx
    ports:
      - 80
    depends_on:
      - php
  php:
    build: ./php
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
    depends_on:
      - database
  database:
    build: ./mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      # - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
